#!/usr/bin/env bash

# ios
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/ios-version-history.js"
echo "module.exports =" >> "src/ios-version-history.js"
cat "./ios-version-history.json" >> "src/ios-version-history.js"

# macos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/macos-version-history.js"
echo "module.exports =" >> "src/macos-version-history.js"
cat "./macos-version-history.json" >> "src/macos-version-history.js"

# tvos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/tvos-version-history.js"
echo "module.exports =" >> "src/tvos-version-history.js"
cat "./tvos-version-history.json" >> "src/tvos-version-history.js"

# watchos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/watchos-version-history.js"
echo "module.exports =" >> "src/watchos-version-history.js"
cat "./watchos-version-history.json" >> "src/watchos-version-history.js"
