#!/usr/bin/env bash

# ios
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/ios-version-history.ts"
echo "export default" >> "src/ios-version-history.ts"
cat "./ios-version-history.json" >> "src/ios-version-history.ts"

# macos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/macos-version-history.ts"
echo "export default" > "src/macos-version-history.ts"
cat "./macos-version-history.json" >> "src/macos-version-history.ts"

# tvos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/tvos-version-history.ts"
echo "export default" > "src/tvos-version-history.ts"
cat "./tvos-version-history.json" >> "src/tvos-version-history.ts"

# watchos
echo "// This file is autogenerated. DO NOT MODIFY IT DIRECTLY." > "src/watchos-version-history.ts"
echo "export default" > "src/watchos-version-history.ts"
cat "./watchos-version-history.json" >> "src/watchos-version-history.ts"
